version: '3'

services:
  api:
    build: . #build the current directory
    ports:
      - '8080:8080'
    environment:
      ENV: 'development'
      PORT: '8080'
      # HOST: "api.example.com" -- defaults to "0.0.0.0"
